# Generated by Django 5.0.6 on 2024-05-21 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_posts_likes_liked_delete_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='liked',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
