# Generated by Django 5.0.6 on 2024-05-23 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_following'),
    ]

    operations = [
        migrations.RenameField(
            model_name='following',
            old_name='owner',
            new_name='follower',
        ),
    ]
